routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route untuk user yang admin
// Route::group(['prefix' => 'admin', 'middleware' => ['auth','role:admin']], function(){
// 	Route::get('/', function(){
// 		// $data['users'] = \App\User::whereDoesntHave('roles')->get();
// 		return view('admin', $data);
// 	});
// });
// Route untuk user yang member

Auth::routes();
// , 'middleware' => ['auth','role:admin']
Route::get('/', function(){
    return redirect('login');
});
Route::get('/jamtersedia', 'PengajuanController@jamtersedia');
Route::group(['prefix' => 'administrator', 'middleware' => ['auth','role:admin']], function () {
    //Index dan user
    Route::get('/', 'DashboardController@index');
    Route::get('/users', 'UserController@users');
    Route::post('/add-user', 'UserController@addAdmin');
    Route::post('/add-dosen', 'UserController@addDosen');
    Route::post('/add-mahasiswa', 'UserController@addMahasiswa');
    Route::get('/dosen', 'UserController@dosen');
    Route::get('/mahasiswa', 'UserController@Mahasiswa');
    //Keahlian;
    Route::resource('keahlian', 'KeahlianController');
    //Pengajuan
    Route::get('/pengajuan', 'PengajuanController@index');
    //Pengaduan
    Route::get('/pengaduan', 'PengaduanController@index');
    Route::get('/process-pengaduan/{id}', 'PengaduanController@processPengaduan');
    //Absen
    Route::get('/absensi', 'WaktuDosen@riwayatabsen');
});
Route::group(['prefix' => 'dosen', 'middleware' => ['auth','role:dosen']], function () {
    Route::get('/', 'DashboardController@indexDosen');
    //pengajuan
    Route::get('/pengajuan', 'PengajuanController@pengajuan');
    Route::get('/get-pengajuan', 'PengajuanController@getPengajuan');
    Route::get('/terima-pengajuan/{id}', 'PengajuanController@terimaPengajuan');
    Route::get('/tolak-pengajuan/{id}', 'PengajuanController@tolakPengajuan');
    //absen
    Route::get('/absensi', 'WaktuDosen@index');
    Route::post('/add-absensi', 'WaktuDosen@addAbsen');
    Route::get('/out-absensi/{id}', 'WaktuDosen@outAbsen');
});
Route::group(['prefix' => 'mahasiswa', 'middleware' => ['auth','role:mahasiswa']], function () {
    Route::get('/', 'DashboardController@indexMahasiswa');
    Route::get('/dosen', 'UserController@getDataDosen');
    Route::get('/find-dosen', 'UserController@findDosen');
    Route::get('/pengajuan', 'PengajuanController@pengajuanMahasiswa');
    Route::post('/add-pengajuan', 'PengajuanController@addPengajuan');
    Route::get('/find-pengajuan', 'PengajuanController@findPengajuan');
    Route::get('/pengaduan', 'PengaduanController@pengaduanMahasiswa');
    Route::post('/add-laporan', 'PengaduanController@addLaporan');
});

resources/views/admin/absensi.blade.php
@extends('layout') @section('sidebar') @include('admin.menu') @endsection @section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-warning">
                    <h4 class="card-title">Riwayat Absensi</h4>
                    <p class="card-category">Berikut adalah list absens yang tercatat</p>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-warning">
                            <th>ID</th>
                            <th>Nama Dosen</th>
                            <th>Waktu Mulai</th>
                            <th>Waktu Selesai</th>
                        </thead>
                        <tbody>

                            @foreach($content as $c)
                            <tr>
                                <td>{{$c->id}}</td>
                                <td>{{$c->users->name}}</td>
                                <td>{{$c->waktu_datang}}</td>
                                <td>{{$c->waktu_pulang}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
 @extends('layout') @section('sidebar') @include('admin.menu') @endsection @section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">content_copy</i>
                    </div>
                    <p class="card-category">Dosen</p>
                    <h3 class="card-title">{{$cdosen}}
                        <small>Orang</small>
                    </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">date_range</i> Lihat Semua
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">content_copy</i>
                    </div>
                    <p class="card-category">Mahasiswa</p>
                    <h3 class="card-title">{{ $cmahasiswa }}
                        <small>Orang</small>
                    </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">date_range</i> Lihat Semua
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-warning">
                    <h4 class="card-title">Pengajuan Terbaru</h4>
                    <p class="card-category">Berikut adalah list pengajuan bimbingan terbaru</p>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-warning">
                            <th>ID</th>
                            <th>Dosen</th>
                            <th>Jenis Pengajuan</th>
                            <th>Waktu</th>
                            <th>Tanggal</th>
                            <th>Status</th>
                        </thead>
                        <tbody>
                        @foreach($content as $c)
                            <tr>
                                <td>{{$c->id}}</td>
                                <td>{{$c->name}}</td>
                                <td>{{$c->des_pengajuan}}</td>
                                <td>{{$c->waktu_pengajuan}}</td>
                                <td>{{$c->tanggal_pengajuan}}</td>
                                <td><a class="btn btn-sm btn-warning">{{$c->status}}</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dosen.blade.php
@extends('layout')

@section('sidebar')
@include('admin.menu')
@endsection @section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Data Dosen</h4>
                    <p class="card-category"> List dosen yang terdaftar di sistem</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <button class="btn btn-primary openModal">Tambah Dosen</button>
                        <table class="table">
                            <thead class=" text-primary">
                                <th>
                                    ID
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Email
                                </th>
                                <th>
                                    Role
                                </th>
                                <th width="200">
                                    Aksi
                                </th>
                            </thead>
                            <tbody>
                                @foreach($content as $c)
                                <tr>
                                    <td>
                                        {{$c->id}}
                                    </td>
                                    <td>
                                        {{$c->name}}
                                    </td>
                                    <td>
                                        {{$c->email}}
                                    </td>
                                    <td>
                                        {{$c->role_name}}
                                    </td>
                                    <td class="text-primary">
                                        <a href="#" class="btn btn-primary btn-sm lihat">Lihat</a>
                                        <a href="#" class="btn btn-success btn-sm ubah">Ubah</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal modalTambah fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Dosen</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form method="post" action="{{url('administrator/add-dosen')}}">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nama</label>
                                <input type="text" class="form-control" name="nama">
                                @csrf
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Email</label>
                                <input type="email" class="form-control" name="email">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Password</label>
                                <input type="password" class="form-control" name="cpassword">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Ulangi Password</label>
                                <input type="password" class="form-control" name="cpassword">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">NIK</label>
                                <input type="text" class="form-control" name="nik">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Keahlian</label>
                                <select class="js-example-basic-multiple form-control" style="width:100%;" name="keahlian[]" multiple="multiple">
                                    @foreach($keahlian as $k)
                                    <option value="{{$k->nama_keahlian}}">{{$k->nama_keahlian}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>

            </form>
        </div>
    </div>
</div>
<div class="modal modalLihat fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Dosen</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nama</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Email</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">NIP</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Keahlian</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal modalubah fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubah Dosen</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nama</label>
                                <input type="text" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Email</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">NIIK</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Keahlian</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Simpan</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('.openModal').on("click", function() {
            $('.modalTambah').modal('show');
        });

        $('.lihat').on("click", function() {
            $('.modalLihat').modal('show');
        });
        $('.ubah').on("click", function() {
            $('.modalubah').modal('show');
        });

        $('.js-example-basic-multiple').select2();
    })
</script>
@endsection

resources/views/admin/keahlian.blade.php
@extends('layout')

@section('sidebar')
@include('admin.menu')
@endsection @section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Data Keahlian</h4>
                    <p class="card-category"> List keahlian yang tercatat di sistem</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif

                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <button class="btn btn-primary tambah">Tambah Keahlian</button>
                        <table class="table">
                            <thead class=" text-primary">
                                <th>
                                    ID
                                </th>
                                <th>
                                    Nama Keahlian
                                </th>
                                <th width="200">
                                    Aksi
                                </th>
                            </thead>
                            <tbody>
                                @foreach($content as $c)
                                <tr>
                                    <td>
                                        {{$c->id}}
                                    </td>
                                    <td>
                                        {{$c->nama_keahlian}}
                                    </td>
                                    <td class="text-primary">
                                        <a href="#" class="btn btn-success btn-sm ubah">Ubah</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal modalTambah fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Keahlian</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{{route('keahlian.store')}}">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @csrf
                                <label class="bmd-label-floating">Nama Keahlian</label>
                                <input type="text" class="form-control" name="nama">
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>

            </form>
        </div>
    </div>
</div>
<div class="modal modalLihat fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Lihat Keahlian</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nama Keahlian</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal modalubah fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubah Keahlian</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nama Keahlian</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Simpan</button>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script>
    $(document).ready(function() {
        $('.tambah').on("click", function() {
            $('.modalTambah').modal('show');
        });

        $('.lihat').on("click", function() {
            ids = $(this).attr('id')
            $.ajax({
                type: 'GET',
                url: '',
                data: {
                    id: ids
                },
                dataType: 'json',
                success: function(data) {
                    // $('.nama').val(data.id_mahasiswa)
                    alert("tes")
                }
            });
            $('.modalLihat').modal('show');
        });
        $('.ubah').on("click", function() {
            $('.modalubah').modal('show');
        });
    })
</script>
@endsection

resources/views/admin/menu.blade.php
<div class="sidebar-wrapper">
    <ul class="nav">
        <li class="nav-item <?php if ($slug == 'dashboard') {
                                echo "active";
                            } ?>">
            <a class="nav-link" href="{{url('/administrator')}}">
                <i class="material-icons">dashboard</i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="nav-item <?php if ($slug == 'pengguna') {
                                echo "active";
                            } ?>">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#0" role="button" aria-haspopup="true" aria-expanded="false"><i class="material-icons">face</i>
                Pengguna</a>

            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{url('administrator/users')}}">Admin</a>
                <a class="dropdown-item" href="{{url('administrator/dosen')}}">Dosen</a>
                <a class="dropdown-item" href="{{url('administrator/mahasiswa')}}">Mahasiswa</a>
            </div>
        </li>
        <li class="nav-item <?php if ($slug == 'absensi') {
                                echo "active";
                            } ?>">
            <a class="nav-link" href="{{url('administrator/absensi')}}">
                <i class="material-icons">content_paste</i>
                <p>Absensi</p>
            </a>
        </li>
        <li class="nav-item <?php if ($slug == 'keahlian') {
                                echo "active";
                            } ?>">
            <a class="nav-link" href="{{url('administrator/keahlian')}}">
                <i class="material-icons">gavel</i>
                <p>Keahlian</p>
            </a>
        </li>
        <li class="nav-item <?php if ($slug == 'pengajuan') {
                                echo "active";
                            } ?>">
            <a class="nav-link" href="{{url('administrator/pengajuan')}}">
                <i class="material-icons">restore</i>
                <p>Pengajuan</p>
            </a>
        </li>
        <li class="nav-item <?php if ($slug == 'pengaduan') {
                                echo "active";
                            } ?>">
            <a class="nav-link" href="{{url('administrator/pengaduan')}}">
                <i class="material-icons">contact_mail</i>
                <p>Pengaduan</p>
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="material-icons">settings_power</i>
                <p>Logout</p>
            </a>
        </li>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>


    </ul>
</div>